/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  alerts: () => import("@/views/alerts/index.vue"),
  blocking_bans: () => import("@/views/blocking/bans/index.vue"),
  "blocking_block-pages": () => import("@/views/blocking/block-pages/index.vue"),
  blocking_bots: () => import("@/views/blocking/bots/index.vue"),
  "blocking_ip-lists": () => import("@/views/blocking/ip-lists/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  guide: () => import("@/views/guide/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "monitoring_error-logs": () => import("@/views/monitoring/error-logs/index.vue"),
  monitoring_events: () => import("@/views/monitoring/events/index.vue"),
  monitoring_monitor: () => import("@/views/monitoring/monitor/index.vue"),
  monitoring_stats: () => import("@/views/monitoring/stats/index.vue"),
  monitoring_traffic: () => import("@/views/monitoring/traffic/index.vue"),
  "protection_rule-perf": () => import("@/views/protection/rule-perf/index.vue"),
  "protection_rule-subs": () => import("@/views/protection/rule-subs/index.vue"),
  protection_rules: () => import("@/views/protection/rules/index.vue"),
  "protection_trigger-records": () => import("@/views/protection/trigger-records/index.vue"),
  "protection_trigger-rules": () => import("@/views/protection/trigger-rules/index.vue"),
  "system_api-tokens": () => import("@/views/system/api-tokens/index.vue"),
  "system_audit-logs": () => import("@/views/system/audit-logs/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_security: () => import("@/views/system/security/index.vue"),
  system_users: () => import("@/views/system/users/index.vue"),
};
