/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  alerts: () => import("@/views/alerts/index.vue"),
  "api-tokens": () => import("@/views/api-tokens/index.vue"),
  "audit-logs": () => import("@/views/audit-logs/index.vue"),
  bans: () => import("@/views/bans/index.vue"),
  "block-pages": () => import("@/views/block-pages/index.vue"),
  bots: () => import("@/views/bots/index.vue"),
  config: () => import("@/views/config/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  events: () => import("@/views/events/index.vue"),
  guide: () => import("@/views/guide/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "ip-lists": () => import("@/views/ip-lists/index.vue"),
  monitor: () => import("@/views/monitor/index.vue"),
  "rule-perf": () => import("@/views/rule-perf/index.vue"),
  rules: () => import("@/views/rules/index.vue"),
  security: () => import("@/views/security/index.vue"),
  traffic: () => import("@/views/traffic/index.vue"),
  "trigger-records": () => import("@/views/trigger-records/index.vue"),
  "trigger-rules": () => import("@/views/trigger-rules/index.vue"),
};
