/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'config',
    path: '/config',
    component: 'layout.base$view.config',
    meta: {
      title: 'config',
      i18nKey: 'route.config',
      icon: 'mdi:cog',
      order: 9
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'mdi:view-dashboard',
      order: 2
    }
  },
  {
    name: 'events',
    path: '/events',
    component: 'layout.base$view.events',
    meta: {
      title: 'events',
      i18nKey: 'route.events',
      icon: 'mdi:shield-alert',
      order: 3
    }
  },
  {
    name: 'guide',
    path: '/guide',
    component: 'layout.base$view.guide',
    meta: {
      title: 'guide',
      i18nKey: 'route.guide',
      icon: 'mdi:book-open-variant',
      order: 10
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'ip-lists',
    path: '/ip-lists',
    component: 'layout.base$view.ip-lists',
    meta: {
      title: 'ip-lists',
      i18nKey: 'route.ip-lists',
      icon: 'mdi:account-group',
      order: 8
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'rules',
    path: '/rules',
    component: 'layout.base$view.rules',
    meta: {
      title: 'rules',
      i18nKey: 'route.rules',
      icon: 'mdi:shield-check-outline',
      order: 5
    }
  },
  {
    name: 'traffic',
    path: '/traffic',
    component: 'layout.base$view.traffic',
    meta: {
      title: 'traffic',
      i18nKey: 'route.traffic',
      icon: 'mdi:chart-timeline-variant',
      order: 4
    }
  },
  {
    name: 'trigger-records',
    path: '/trigger-records',
    component: 'layout.base$view.trigger-records',
    meta: {
      title: 'trigger-records',
      i18nKey: 'route.trigger-records',
      icon: 'mdi:history',
      order: 7
    }
  },
  {
    name: 'trigger-rules',
    path: '/trigger-rules',
    component: 'layout.base$view.trigger-rules',
    meta: {
      title: 'trigger-rules',
      i18nKey: 'route.trigger-rules',
      icon: 'mdi:filter-variant',
      order: 6
    }
  }
];
