/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'alerts',
    path: '/alerts',
    component: 'layout.base$view.alerts',
    meta: {
      title: 'alerts',
      i18nKey: 'route.alerts',
      icon: 'mdi:bell-ring-outline',
      order: 6
    }
  },
  {
    name: 'api-tokens',
    path: '/api-tokens',
    component: 'layout.base$view.api-tokens',
    meta: {
      title: 'api-tokens',
      i18nKey: 'route.api-tokens'
    }
  },
  {
    name: 'audit-logs',
    path: '/audit-logs',
    component: 'layout.base$view.audit-logs',
    meta: {
      title: 'audit-logs',
      i18nKey: 'route.audit-logs'
    }
  },
  {
    name: 'bans',
    path: '/bans',
    component: 'layout.base$view.bans',
    meta: {
      title: 'bans',
      i18nKey: 'route.bans'
    }
  },
  {
    name: 'block-pages',
    path: '/block-pages',
    component: 'layout.base$view.block-pages',
    meta: {
      title: 'block-pages',
      i18nKey: 'route.block-pages'
    }
  },
  {
    name: 'bots',
    path: '/bots',
    component: 'layout.base$view.bots',
    meta: {
      title: 'bots',
      i18nKey: 'route.bots'
    }
  },
  {
    name: 'config',
    path: '/config',
    component: 'layout.base$view.config',
    meta: {
      title: 'config',
      i18nKey: 'route.config'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'mdi:view-dashboard',
      order: 2
    }
  },
  {
    name: 'error-logs',
    path: '/error-logs',
    component: 'layout.base$view.error-logs',
    meta: {
      title: 'error-logs',
      i18nKey: 'route.error-logs'
    }
  },
  {
    name: 'events',
    path: '/events',
    component: 'layout.base$view.events',
    meta: {
      title: 'events',
      i18nKey: 'route.events'
    }
  },
  {
    name: 'guide',
    path: '/guide',
    component: 'layout.base$view.guide',
    meta: {
      title: 'guide',
      i18nKey: 'route.guide',
      icon: 'mdi:book-open-variant',
      order: 8
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'ip-lists',
    path: '/ip-lists',
    component: 'layout.base$view.ip-lists',
    meta: {
      title: 'ip-lists',
      i18nKey: 'route.ip-lists'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base$view.monitor',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    }
  },
  {
    name: 'rule-perf',
    path: '/rule-perf',
    component: 'layout.base$view.rule-perf',
    meta: {
      title: 'rule-perf',
      i18nKey: 'route.rule-perf'
    }
  },
  {
    name: 'rule-subs',
    path: '/rule-subs',
    component: 'layout.base$view.rule-subs',
    meta: {
      title: 'rule-subs',
      i18nKey: 'route.rule-subs'
    }
  },
  {
    name: 'rules',
    path: '/rules',
    component: 'layout.base$view.rules',
    meta: {
      title: 'rules',
      i18nKey: 'route.rules'
    }
  },
  {
    name: 'security',
    path: '/security',
    component: 'layout.base$view.security',
    meta: {
      title: 'security',
      i18nKey: 'route.security'
    }
  },
  {
    name: 'traffic',
    path: '/traffic',
    component: 'layout.base$view.traffic',
    meta: {
      title: 'traffic',
      i18nKey: 'route.traffic'
    }
  },
  {
    name: 'trigger-records',
    path: '/trigger-records',
    component: 'layout.base$view.trigger-records',
    meta: {
      title: 'trigger-records',
      i18nKey: 'route.trigger-records'
    }
  },
  {
    name: 'trigger-rules',
    path: '/trigger-rules',
    component: 'layout.base$view.trigger-rules',
    meta: {
      title: 'trigger-rules',
      i18nKey: 'route.trigger-rules'
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users'
    }
  }
];
