package model

// SeedRules 内置规则种子：后台首次启动时导入 Rule 表，作为出厂基线防护。
// 与 waf/ruleset/builtin.lua 保持一致；导入后可在管理后台增删改。
var SeedRules = []Rule{
	// ---- 敏感文件 / 扫描器 ----
	{RuleID: "10001", Name: "敏感文件泄露拦截", Group: "leak", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `\.(git|svn|hg)(/|$)|(^|/)(\.env|\.bash_history|\.DS_Store|config\.php\.bak|web\.config\.bak)(/|$)|\.(sql|bak|tar\.gz|zip|log)$`,
		Transforms: `["url_decode","to_lowercase"]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"敏感文件泄露拦截"}`, Status: 403, Message: "敏感文件泄露拦截", SortOrder: 1},
	{RuleID: "10002", Name: "扫描器 UA 拦截", Group: "scanner", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `(sqlmap|nikto|nmap|nessus|acunetix|wpscan|masscan|zgrab|hydra|dirbuster|gobuster)`,
		Transforms: `["to_lowercase"]`, Vars: `[{"type":"HEADERS","specific":"user-agent"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"扫描器 UA 拦截"}`, Status: 403, Message: "扫描器 UA 拦截", SortOrder: 2},

	// ---- SQL 注入 ----
	{RuleID: "20001", Name: "SQL 注入：union select", Group: "sqli", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\bunion\b[\s\S]{0,100}?\bselect\b`,
		Transforms: `["url_decode","to_lowercase","remove_comments","compress_whitespace"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SQL 注入：union select"}`, Status: 403, Message: "SQL 注入：union select", SortOrder: 10},
	{RuleID: "20002", Name: "SQL 注入：延时探测", Group: "sqli", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\b(sleep|benchmark|waitfor)\s*\(`,
		Transforms: `["url_decode","to_lowercase","remove_comments"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SQL 注入：延时探测"}`, Status: 403, Message: "SQL 注入：延时探测", SortOrder: 11},
	{RuleID: "20003", Name: "SQL 注入：information_schema", Group: "sqli", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\binformation_schema\b`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SQL 注入：information_schema"}`, Status: 403, Message: "SQL 注入：information_schema", SortOrder: 12},
	{RuleID: "20004", Name: "SQL 注入：布尔盲注", Group: "sqli", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\b(and|or)\s+\d{1,4}\s*[=<>!]{1,2}\s*\d{1,4}`,
		Transforms: `["url_decode","to_lowercase","remove_comments"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SQL 注入：布尔盲注"}`, Status: 403, Message: "SQL 注入：布尔盲注", SortOrder: 13},
	{RuleID: "20005", Name: "SQL 注入：注释混淆", Group: "sqli", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `/\*!?\d*\s*(union|select|from|where|insert|update|delete|drop|alter|truncate|exec)`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SQL 注入：注释混淆"}`, Status: 403, Message: "SQL 注入：注释混淆", SortOrder: 14},
	{RuleID: "20006", Name: "SQL 注入：文件读写", Group: "sqli", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\b(load_file|into\s+outfile|into\s+dumpfile|into\s+loadfile)\b`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SQL 注入：文件读写"}`, Status: 403, Message: "SQL 注入：文件读写", SortOrder: 15},

	// ---- XSS ----
	{RuleID: "21001", Name: "XSS：脚本标签", Group: "xss", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `<(script|iframe|object|embed|applet)[^>]*>`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"XSS：脚本标签"}`, Status: 403, Message: "XSS：脚本标签", SortOrder: 20},
	{RuleID: "21002", Name: "XSS：事件处理器", Group: "xss", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `\bon(load|error|click|mouseover|mouseout|focus|blur|change|submit|keydown|keyup)\s*=\s*['"]?[^'">]{1,200}`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"XSS：事件处理器"}`, Status: 403, Message: "XSS：事件处理器", SortOrder: 21},
	{RuleID: "21003", Name: "XSS：危险协议", Group: "xss", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `(javascript:|vbscript:|data:text/html|expression\s*\()`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"XSS：危险协议"}`, Status: 403, Message: "XSS：危险协议", SortOrder: 22},
	{RuleID: "21004", Name: "XSS：脚本函数", Group: "xss", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `\b(alert|prompt|confirm|document\.cookie|window\.location)\s*\(`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"XSS：脚本函数"}`, Status: 403, Message: "XSS：脚本函数", SortOrder: 23},

	// ---- 命令执行 ----
	{RuleID: "22001", Name: "命令执行：命令拼接", Group: "rce", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `(;|\|\||&&|` + "`" + `)\s*(id|whoami|pwd|uname|cat\s|ls\s|wget|curl|nc\s|bash\s|sh\s|chmod\s|kill\s|reboot|shutdown)`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"命令执行：命令拼接"}`, Status: 403, Message: "命令执行：命令拼接", SortOrder: 30},
	{RuleID: "22002", Name: "命令执行：读取系统文件", Group: "rce", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\b(cat|tac|tail|head|more|less)\s+(/etc/passwd|/etc/shadow|/etc/hosts)`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"命令执行：读取系统文件"}`, Status: 403, Message: "命令执行：读取系统文件", SortOrder: 31},
	{RuleID: "22003", Name: "命令执行：危险函数", Group: "rce", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\b(system|exec|passthru|shell_exec|popen|proc_open|pcntl_exec|assert|eval)\s*\(`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"命令执行：危险函数"}`, Status: 403, Message: "命令执行：危险函数", SortOrder: 32},

	// ---- 文件包含 / 路径穿越 ----
	{RuleID: "23001", Name: "路径穿越", Group: "lfi", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `(\.\./|\.\.\\|%2e%2e%2f)`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI"},{"type":"URI_ARGS"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"路径穿越"}`, Status: 403, Message: "路径穿越", SortOrder: 40},
	{RuleID: "23002", Name: "敏感系统文件访问", Group: "lfi", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `((^|/)etc/(passwd|shadow|group|hosts)(/|$)|(^|/)windows/(win\.ini|system32)(/|$))`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI"},{"type":"URI_ARGS"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"敏感系统文件访问"}`, Status: 403, Message: "敏感系统文件访问", SortOrder: 41},
	{RuleID: "23003", Name: "危险协议包装器", Group: "lfi", Phase: "access", Severity: 3, Enabled: true,
		Operator: "REGEX", Pattern: `\b(file|php|zip|phar|data|expect|ftp)://`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"危险协议包装器"}`, Status: 403, Message: "危险协议包装器", SortOrder: 42},

	// ---- SSRF ----
	{RuleID: "24001", Name: "SSRF：内网/本地地址", Group: "ssrf", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `https?://(127\.0\.0\.1|localhost|0\.0\.0\.0|10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2[0-9]|3[01])\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3})`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"},{"type":"BODY"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SSRF：内网/本地地址"}`, Status: 403, Message: "SSRF：内网/本地地址", SortOrder: 50},
	{RuleID: "24002", Name: "SSRF：云元数据地址", Group: "ssrf", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `(169\.254\.169\.254|metadata\.google\.internal|100\.100\.100\.200)`,
		Transforms: `["url_decode","to_lowercase"]`,
		Vars:       `[{"type":"URI_ARGS"},{"type":"POST_ARGS"}]`,
		Actions:    `{"disrupt":"BLOCK","status":403,"msg":"SSRF：云元数据地址"}`, Status: 403, Message: "SSRF：云元数据地址", SortOrder: 51},

	// ---- 协议异常 ----
	{RuleID: "25001", Name: "非标准 HTTP 方法", Group: "protocol", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `^(?!(get|post|put|delete|head|options|patch|connect|trace)$).+$`,
		Transforms: `["to_lowercase"]`,
		Vars:       `[{"type":"METHOD"}]`,
		Actions:    `{"disrupt":"BLOCK","status":405,"msg":"非标准 HTTP 方法"}`, Status: 405, Message: "非标准 HTTP 方法", SortOrder: 60},
	{RuleID: "25002", Name: "请求 URI 过长", Group: "protocol", Phase: "access", Severity: 2, Enabled: true,
		Operator: "REGEX", Pattern: `.{8192,}`,
		Transforms: `[]`,
		Vars:       `[{"type":"REQUEST_URI"}]`,
		Actions:    `{"disrupt":"BLOCK","status":414,"msg":"请求 URI 过长"}`, Status: 414, Message: "请求 URI 过长", SortOrder: 61},
}
