// Code generated from chaitin/safeline libfusion2.so HW ruleset (逆向提取). DO NOT EDIT BY HAND.
package model

// SeedRulesCVE 雷池(SafeLine) 检测引擎内置 CVE/HW 指纹规则转译（逆向 libfusion2.so 规则库提取）
// 来源：safeline-detector:9.4.0 libfusion2.so 内嵌 rules 库（374 条 HW 规则中的高价值单条件部分）
// 映射：decoded_path→URI、decoded_query/query→URI_ARGS、request_body→BODY、form→POST_ARGS、
//
//	custom_header/cookie/user_agent/xff/referer/host/content_type→HEADERS/COOKIE 对应变量
//
// 双字段规则：key 精确→specific 取指定参数；key 为正则→parse=["keys"] 同时收集键名以匹配键名特征
// 等级：risk=3 默认 BLOCK 403；risk=1/2 默认 LOG_ONLY（后台可改 BLOCK）
var SeedRulesCVE = []Rule{
	{RuleID: "65712", Name: "利用 Apache 解析漏洞来执行 PHP 脚本", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(up|down)load.*\.php\d*\.[^\/]+`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：利用 Apache 解析漏洞来执行 PHP 脚本"}`, Status: 403, Message: "CVE 指纹：利用 Apache 解析漏洞来执行 PHP 脚本", SortOrder: 1000},
	{RuleID: "65722", Name: "Apache Kylin 未授权配置 (CVE-2020-13937)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)/+kylin/+api/+admin/+config`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Apache Kylin 未授权配置 (CVE-2020-13937)"}`, Status: 403, Message: "CVE 指纹：Apache Kylin 未授权配置 (CVE-2020-13937)", SortOrder: 1001},
	{RuleID: "65761", Name: "Atlassian Crowd 未授权访问 (CVE-2019-11580)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)/crowd/admin/uploadplugin\.action`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Atlassian Crowd 未授权访问 (CVE-2019-11580)"}`, Status: 403, Message: "CVE 指纹：Atlassian Crowd 未授权访问 (CVE-2019-11580)", SortOrder: 1002},
	{RuleID: "65600", Name: "扫描 IIS 短文件名 / 文件夹", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\/[\w\d\?]{0,6}\*~\d[\*\.\/])`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：扫描 IIS 短文件名 / 文件夹"}`, Status: 403, Message: "CVE 指纹：扫描 IIS 短文件名 / 文件夹", SortOrder: 1003},
	{RuleID: "65602", Name: "IIS 扩展名漏洞 (CVE-2009-4444)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(.*\.(asp|cer|asa);)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：IIS 扩展名漏洞 (CVE-2009-4444)"}`, Status: 403, Message: "CVE 指纹：IIS 扩展名漏洞 (CVE-2009-4444)", SortOrder: 1004},
	{RuleID: "65628", Name: "Nginx code 解析漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\..*\x00.*\.php\d*)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Nginx code 解析漏洞"}`, Status: 403, Message: "CVE 指纹：Nginx code 解析漏洞", SortOrder: 1005},
	{RuleID: "65660", Name: "spring 目录遍历 (cve-2014-3625)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `spring-css\/resources\/file:`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：spring 目录遍历 (cve-2014-3625)"}`, Status: 403, Message: "CVE 指纹：spring 目录遍历 (cve-2014-3625)", SortOrder: 1006},
	{RuleID: "65667", Name: "Spring Cloud Config 路径穿越漏洞 (CVE-2020-5405)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\.\.\(_\)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Spring Cloud Config 路径穿越漏洞 (CVE-2020-5405)"}`, Status: 403, Message: "CVE 指纹：Spring Cloud Config 路径穿越漏洞 (CVE-2020-5405)", SortOrder: 1007},
	{RuleID: "65848", Name: "Spring Boot Actuator敏感信息泄露漏洞", Group: "cve", Phase: "access", Severity: 1, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/actuator\/((auditevents|archaius|nacosconfig|nacosdiscovery|beans|conditions|heapdump|threaddump|scheduledtasks|mappings|refresh|features|service-registry|flyway|httpexchanges|integrationgraph|liquibase|logfile|prometheus|quartz|shutdown|startup)$|(caches|env|loggers|metrics|sessions|quartz\/jobs|configprops|quartz\/triggers)($|\/))`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：Spring Boot Actuator敏感信息泄露漏洞"}`, Status: 200, Message: "CVE 指纹：Spring Boot Actuator敏感信息泄露漏洞", SortOrder: 1008},
	{RuleID: "65719", Name: "phpinfo 泄露", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(phpinfo)[\\-_]*\d*\.(php)\d*([^\w\d]|$)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：phpinfo 泄露"}`, Status: 200, Message: "CVE 指纹：phpinfo 泄露", SortOrder: 1009},
	{RuleID: "65879", Name: "ThinkPHP5 远程代码执行漏洞-path", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `think\\(?i)(app\/invokefunction|loader|error|container|env|config|hook|facade|db|lang|request|log|route|middleware|cookie|view|template|session|debug|cache)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：ThinkPHP5 远程代码执行漏洞-path"}`, Status: 403, Message: "CVE 指纹：ThinkPHP5 远程代码执行漏洞-path", SortOrder: 1010},
	{RuleID: "65580", Name: "[HW2020] Druid 未授权访问", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(/druid/websession\.html|/system/druid/websession\.html|/webpage/system/druid/websession\.html|/druid/login\.html|/system/druid/login\.html|/webpage/system/druid/login\.html)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] Druid 未授权访问"}`, Status: 403, Message: "CVE 指纹：[HW2020] Druid 未授权访问", SortOrder: 1011},
	{RuleID: "65563", Name: "[HW2020] GoAhead RCE (CVE-2017-17562)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `/cgi-bin/c8fed00eb2e87f1cee8e90ebbe870c190ac3848c`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] GoAhead RCE (CVE-2017-17562)"}`, Status: 403, Message: "CVE 指纹：[HW2020] GoAhead RCE (CVE-2017-17562)", SortOrder: 1012},
	{RuleID: "65565", Name: "[HW2020] Apache Spark 未授权访问", Group: "cve", Phase: "access", Severity: 1, Enabled: true,
		Operator: `REGEX`, Pattern: `/v1/submissions/create`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：[HW2020] Apache Spark 未授权访问"}`, Status: 200, Message: "CVE 指纹：[HW2020] Apache Spark 未授权访问", SortOrder: 1013},
	{RuleID: "65669", Name: "访问备份或临时文件的请求", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\.(bak|back|backup|temp|tmp|sql|old|swp)$`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：访问备份或临时文件的请求"}`, Status: 200, Message: "CVE 指纹：访问备份或临时文件的请求", SortOrder: 1014},
	{RuleID: "65647", Name: "访问 SVN 仓库的请求", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))\.svn((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))entries`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：访问 SVN 仓库的请求"}`, Status: 403, Message: "CVE 指纹：访问 SVN 仓库的请求", SortOrder: 1015},
	{RuleID: "65679", Name: "泛微 E-cology OA远程代码执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\/bsh\.servlet\.BshServlet`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：泛微 E-cology OA远程代码执行"}`, Status: 403, Message: "CVE 指纹：泛微 E-cology OA远程代码执行", SortOrder: 1016},
	{RuleID: "65688", Name: "[HW2022] Weblogic Server 信息泄漏漏洞利用 (CVE-2022-21371)", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)/WEB-INF/(.+/)*(\w|_|-)+\.(properties|xml)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：[HW2022] Weblogic Server 信息泄漏漏洞利用 (CVE-2022-21371)"}`, Status: 200, Message: "CVE 指纹：[HW2022] Weblogic Server 信息泄漏漏洞利用 (CVE-2022-21371)", SortOrder: 1017},
	{RuleID: "65723", Name: "快排CMS 未授权访问 ", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^/+kuaipai/+runtime/+log/+[0-9]+/+[0-9]+\.log`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：快排CMS 未授权访问 "}`, Status: 403, Message: "CVE 指纹：快排CMS 未授权访问 ", SortOrder: 1018},
	{RuleID: "65747", Name: "RichFaces 远程代码执行 (CVE-2018-14667)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)/+a4j/+s/3_3_3\.Finalorg\.ajax4jsf\.resource\.UserResource`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：RichFaces 远程代码执行 (CVE-2018-14667)"}`, Status: 403, Message: "CVE 指纹：RichFaces 远程代码执行 (CVE-2018-14667)", SortOrder: 1019},
	{RuleID: "65757", Name: "CRLF 注入", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\r\n|\n)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：CRLF 注入"}`, Status: 200, Message: "CVE 指纹：CRLF 注入", SortOrder: 1020},
	{RuleID: "65758", Name: "CRLF 注入", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\r\n|\n).*(\r\n|\n)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：CRLF 注入"}`, Status: 403, Message: "CVE 指纹：CRLF 注入", SortOrder: 1021},
	{RuleID: "65781", Name: "[HW2023] TPLINK WR941N V2 后门", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^/userRpmNatDebugRpm26525557/linux_cmdline.html`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] TPLINK WR941N V2 后门"}`, Status: 403, Message: "CVE 指纹：[HW2023] TPLINK WR941N V2 后门", SortOrder: 1022},
	{RuleID: "65779", Name: "[HW2023] Yongyou 命令执行 by actionhandlerservlet", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^/servlet/~ic/com\.ufida\.zior\.console\.ActionHandlerServlet`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] Yongyou 命令执行 by actionhandlerservlet"}`, Status: 403, Message: "CVE 指纹：[HW2023] Yongyou 命令执行 by actionhandlerservlet", SortOrder: 1023},
	{RuleID: "65780", Name: "[HW2023] 用友 命令执行 by ncmessageservlet", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^/servlet/~baseapp/nc\.message\.bs\.NCMessageServlet`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] 用友 命令执行 by ncmessageservlet"}`, Status: 403, Message: "CVE 指纹：[HW2023] 用友 命令执行 by ncmessageservlet", SortOrder: 1024},
	{RuleID: "65782", Name: "[HW2023] 用友 命令执行 by uploadservlet", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^/servlet/~ncwebpub/nc\.document\.pub\.fileSystem\.servlet\.UploadServlet`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] 用友 命令执行 by uploadservlet"}`, Status: 403, Message: "CVE 指纹：[HW2023] 用友 命令执行 by uploadservlet", SortOrder: 1025},
	{RuleID: "65798", Name: "[HW2023] 大华智慧园区综合管理平台任意密码读取漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/+admin/+user_getUserInfoByUserName\.action`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] 大华智慧园区综合管理平台任意密码读取漏洞"}`, Status: 403, Message: "CVE 指纹：[HW2023] 大华智慧园区综合管理平台任意密码读取漏洞", SortOrder: 1026},
	{RuleID: "65804", Name: "[HW2023] Jeecg-Boot JDBC 远程代码执行漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/+jeecg-boot\/+jmreport\/+testConnection|\/+jmreport\/+testConnection`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] Jeecg-Boot JDBC 远程代码执行漏洞"}`, Status: 403, Message: "CVE 指纹：[HW2023] Jeecg-Boot JDBC 远程代码执行漏洞", SortOrder: 1027},
	{RuleID: "65807", Name: "[HW2023] 帆软报表channel反序列化漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/+\s*decision(([;. ]*)|(\;(.*)))\/\s*remote(([;. ]*)|(\;(.*)))\/\s*design(([;. ]*)|(\;(.*)))\/\s*channel`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] 帆软报表channel反序列化漏洞"}`, Status: 403, Message: "CVE 指纹：[HW2023] 帆软报表channel反序列化漏洞", SortOrder: 1028},
	{RuleID: "65833", Name: "Jeecg-boot v2.1.2-v3.0.0 后台未授权SQL注入漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/+sys\/+ng(-)?alain\/+getDictItemsByTable\/+(([^\/]*['"*][^\/]*\/+[^\/]*['"*])|([^\/]*\/+[^\/]*['"*]))`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Jeecg-boot v2.1.2-v3.0.0 后台未授权SQL注入漏洞"}`, Status: 403, Message: "CVE 指纹：Jeecg-boot v2.1.2-v3.0.0 后台未授权SQL注入漏洞", SortOrder: 1029},
	{RuleID: "65847", Name: "D-Link D-View 8 v2.0.1.28 未授权访问 (CVE-2023-5074)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\.?\/)+dview8(\.?\/)+api(\.?\/)+usersByLevel`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：D-Link D-View 8 v2.0.1.28 未授权访问 (CVE-2023-5074)"}`, Status: 403, Message: "CVE 指纹：D-Link D-View 8 v2.0.1.28 未授权访问 (CVE-2023-5074)", SortOrder: 1030},
	{RuleID: "65855", Name: "[HW2024] 海康威视综合安防系统 detection接口 远程代码执行漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/+center\/+api\/+installation\/+detection`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2024] 海康威视综合安防系统 detection接口 远程代码执行漏洞"}`, Status: 403, Message: "CVE 指纹：[HW2024] 海康威视综合安防系统 detection接口 远程代码执行漏洞", SortOrder: 1031},
	{RuleID: "65856", Name: "[HW2024] 浪潮GSP企业管理软件 bizintegrationwebservice.asmx 远程代码执行漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\/+cwbase\/+gsp\/+webservice\/+bizintegrationwebservice\/+bizintegrationwebservice\.asmx`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2024] 浪潮GSP企业管理软件 bizintegrationwebservice.asmx 远程代码执行漏洞"}`, Status: 403, Message: "CVE 指纹：[HW2024] 浪潮GSP企业管理软件 bizintegrationwebservice.asmx 远程代码执行漏洞", SortOrder: 1032},
	{RuleID: "65792", Name: "企业微信信息泄露", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)/+cgi-bin/+gateway/+agentinfo`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：企业微信信息泄露"}`, Status: 403, Message: "CVE 指纹：企业微信信息泄露", SortOrder: 1033},
	{RuleID: "65595", Name: "后门", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))((((web|php)?shell)|(php|jsp)?spy)|(zecmd|wooyun|cmdexec|muma|attack))[\-_]?\d*\.(php\d*|jsp|aspx?|asa|cer|cgi)[\/;]?([^\w\d]|$)`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：后门"}`, Status: 403, Message: "CVE 指纹：后门", SortOrder: 1034},
	{RuleID: "65605", Name: "[HW2021] Apache Shiro 权限绕过漏洞(CVE-2020-13933)", Group: "cve", Phase: "access", Severity: 1, Enabled: true,
		Operator: `REGEX`, Pattern: `/;`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：[HW2021] Apache Shiro 权限绕过漏洞(CVE-2020-13933)"}`, Status: 200, Message: "CVE 指纹：[HW2021] Apache Shiro 权限绕过漏洞(CVE-2020-13933)", SortOrder: 1035},
	{RuleID: "65606", Name: "[HW2021] Apache Shiro身份认证绕过漏洞(CVE-2020-17523)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `[\x20\x2e]\/?$`,
		Transforms: `[]`, Vars: `[{"type":"URI"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2021] Apache Shiro身份认证绕过漏洞(CVE-2020-17523)"}`, Status: 403, Message: "CVE 指纹：[HW2021] Apache Shiro身份认证绕过漏洞(CVE-2020-17523)", SortOrder: 1036},
	{RuleID: "65713", Name: "Apache HTTPD SSRF (CVE-2021-40438)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)unix:.{100,}\|.*`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Apache HTTPD SSRF (CVE-2021-40438)"}`, Status: 403, Message: "CVE 指纹：Apache HTTPD SSRF (CVE-2021-40438)", SortOrder: 1037},
	{RuleID: "65635", Name: "Struts2 S2-020", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(.*[^_0-9a-zA-Z])?(action|Redirect|redirectAction)([^_0-9a-zA-Z].*)?:.*\{.+xwork2\.dispatcher.*\}`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Struts2 S2-020"}`, Status: 403, Message: "CVE 指纹：Struts2 S2-020", SortOrder: 1038},
	{RuleID: "65643", Name: "Struts2 S2-005", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)xwork\.MethodAccessor\.denyMethodExecution.*\\u003d*false['"\)]{1,2}.*java\.lang\.Runtime@getRuntime\(\)`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Struts2 S2-005"}`, Status: 403, Message: "CVE 指纹：Struts2 S2-005", SortOrder: 1039},
	{RuleID: "65644", Name: "Struts2 S2-016", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(new.+java\s*\.\s*lang|\.\s*dispatcher\s*\.\s*HttpServletRequest)`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Struts2 S2-016"}`, Status: 403, Message: "CVE 指纹：Struts2 S2-016", SortOrder: 1040},
	{RuleID: "65593", Name: "ThinkPHP5 任意代码执行漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `think\\(?i)(app\/invokefunction|loader|error|container|env|config|hook|facade|db|lang|request|log|route|middleware|cookie|view|template|session|debug|cache)`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：ThinkPHP5 任意代码执行漏洞"}`, Status: 403, Message: "CVE 指纹：ThinkPHP5 任意代码执行漏洞", SortOrder: 1041},
	{RuleID: "65654", Name: "Jenkins 非预期方法调用漏洞(SECURITY-595)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)value=[\s\S]*((([^_0-9a-zA-Z]groovy\s*\.\s*transform\s*\.)|(@GrabResolver\s*\()))`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Jenkins 非预期方法调用漏洞(SECURITY-595)"}`, Status: 403, Message: "CVE 指纹：Jenkins 非预期方法调用漏洞(SECURITY-595)", SortOrder: 1042},
	{RuleID: "65646", Name: "PHP168 代码执行漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)showHtml_Type\[bencandy\]\[.*\]=\{\$\{.*\}\}`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：PHP168 代码执行漏洞"}`, Status: 403, Message: "CVE 指纹：PHP168 代码执行漏洞", SortOrder: 1043},
	{RuleID: "65689", Name: "[HW2022] Weblogic Server 信息泄漏漏洞利用", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)/WEB-INF/.*/(\w|_|-)+\.(properties|xml)`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：[HW2022] Weblogic Server 信息泄漏漏洞利用"}`, Status: 200, Message: "CVE 指纹：[HW2022] Weblogic Server 信息泄漏漏洞利用", SortOrder: 1044},
	{RuleID: "65849", Name: "[HW2024] PHP-CGI Windows平台远程代码执行漏洞(cve-2024-4577)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\xad|%ad)d.*(php_ini_loaded_file|open_basedir|include_path|auto_prepend_file|extension_dir|allow_url_fopen|allow_url_include|short_open_tag|ignore_repeated_errors|ignore_repeated_source|register_argc_argv|enable_dl|file_uploads|disable_functions|disable_classes)`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2024] PHP-CGI Windows平台远程代码执行漏洞(cve-2024-4577)"}`, Status: 403, Message: "CVE 指纹：[HW2024] PHP-CGI Windows平台远程代码执行漏洞(cve-2024-4577)", SortOrder: 1045},
	{RuleID: "65549", Name: "[HW2020] S2-005 (1) (CVE-2010-1870)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `context\[xwork.MethodAccessor\.denyMethodExecution\]`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] S2-005 (1) (CVE-2010-1870)"}`, Status: 403, Message: "CVE 指纹：[HW2020] S2-005 (1) (CVE-2010-1870)", SortOrder: 1046},
	{RuleID: "65844", Name: "XML 实体注入漏洞 (UTF-16)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((\x00|%00)?(<|%3C)(\x00|%00)(!|%21)(\x00|%00)(E|%45)(\x00|%00)(N|%4E)(\x00|%00)(T|%54)(\x00|%00)(I|49)(\x00|%00)(T|%54)(\x00|%00)(Y|%59)(\x00|%00)?).{5,100}(\x00|%00)?((S|%53)(\x00|%00)(Y|%59)(\x00|%00)(S|%53)(\x00|%00)(T|%54)(\x00|%00)(E|%45)(\x00|%00)(M|%4D)|(P|%50)(\x00|%00)(U|%55)(\x00|%00)(B|%42)(\x00|%00)(L|%4C)(\x00|%00)(I|%49)(\x00|%00)(C|%43))(\x00|%00)?`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：XML 实体注入漏洞 (UTF-16)"}`, Status: 403, Message: "CVE 指纹：XML 实体注入漏洞 (UTF-16)", SortOrder: 1047},
	{RuleID: "65653", Name: "Atlassian Jira 服务端请求伪造漏洞 (CVE-2022-26135)", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `^\s*\{.*"requests"\s*:\s*\[.*"method".*"location"\s*:\s*"\s*@`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：Atlassian Jira 服务端请求伪造漏洞 (CVE-2022-26135)"}`, Status: 200, Message: "CVE 指纹：Atlassian Jira 服务端请求伪造漏洞 (CVE-2022-26135)", SortOrder: 1048},
	{RuleID: "65692", Name: "F5 BIG-IP漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)call\s+"org\.hsqldb\.util\.ScriptTool\.main"\('[a-zA-Z0-9]+'\);`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：F5 BIG-IP漏洞"}`, Status: 403, Message: "CVE 指纹：F5 BIG-IP漏洞", SortOrder: 1049},
	{RuleID: "65704", Name: "访问系统文件的请求", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i).*[^\w](((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))(((\.)|((\xc0(\x2e|\x6e|\xae|\xee)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2e|6e|ae|ee)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2e))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0e|002e))|((\xef\xbc\x8e)))((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))+)?)+((etc(((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))(((\.)|((\xc0(\x2e|\x6e|\xae|\xee)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2e|6e|ae|ee)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2e))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0e|002e))|((\xef\xbc\x8e)))((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))+)?)+(passwd-?|shadow|cron\.d|group|gshadow|shells|hosts))|(root(((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))(((\.)|((\xc0(\x2e|\x6e|\xae|\xee)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2e|6e|ae|ee)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2e))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0e|002e))|((\xef\xbc\x8e)))((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))+)?)+(\.ssh))|(bin(((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))(((\.)|((\xc0(\x2e|\x6e|\xae|\xee)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2e|6e|ae|ee)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2e))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0e|002e))|((\xef\xbc\x8e)))((\\|\/)|((\xc0(\x2f|\x6f|\xaf|\xef))|(\xc1(\x1c|\x5c|\x9c|\xdc)))|(((((%|=)(25)?)(%(32|35))?)c0(((%|=)(25)?)(%(32|35))?)(2f|6f|af|ef))|((((%|=)(25)?)(%(32|35))?)c1(((%|=)(25)?)(%(32|35))?)(1c|5c|9c|dc)))|((0x|\\x?|(((%|=)(25)?)(%(32|35))?))(2f|5c))|(((((%|=)(25)?)(%(32|35))?)|\\)u(ff0f|ff3c|2215|2216))|((\xef\xbc\x8f)|(\xef\xbc\xbc)))+)?)+(sh|bash|ifconfig|wget|curl|sudo|su)))\b`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：访问系统文件的请求"}`, Status: 403, Message: "CVE 指纹：访问系统文件的请求", SortOrder: 1050},
	{RuleID: "65548", Name: "[HW2020] ImageMagick RCE (CVE-2016-3714)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `push\s+graphic-context.*viewbox.*pop\s+graphic-context`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] ImageMagick RCE (CVE-2016-3714)"}`, Status: 403, Message: "CVE 指纹：[HW2020] ImageMagick RCE (CVE-2016-3714)", SortOrder: 1051},
	{RuleID: "65550", Name: "[HW2020] S2-005 (2) (CVE-2010-1870)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `context\[xwork.MethodAccessor\.denyMethodExecution\]`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] S2-005 (2) (CVE-2010-1870)"}`, Status: 403, Message: "CVE 指纹：[HW2020] S2-005 (2) (CVE-2010-1870)", SortOrder: 1052},
	{RuleID: "65553", Name: "[HW2020] Spring RCE (CVE-2018-1270)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\["SUBSCRIBE\s+selector:T\(java\.lang.*"\]`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] Spring RCE (CVE-2018-1270)"}`, Status: 403, Message: "CVE 指纹：[HW2020] Spring RCE (CVE-2018-1270)", SortOrder: 1053},
	{RuleID: "65555", Name: "[HW2020] ElasticSearch 命令执行 (CVE-2015-1427)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\{.*"script_fields".*\{.*"script"\s*:\s*"java\.lang.*\}.*\}`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] ElasticSearch 命令执行 (CVE-2015-1427)"}`, Status: 403, Message: "CVE 指纹：[HW2020] ElasticSearch 命令执行 (CVE-2015-1427)", SortOrder: 1054},
	{RuleID: "65561", Name: "[HW2020] ffmpeg 文件读取 (CVE-2016-1897)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `#EXTM3U.*(#EXT-X-TARGETDURATION|#EXT-X-MEDIA-SEQUENCE).*https?://.*#EXT-X-ENDLIST`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] ffmpeg 文件读取 (CVE-2016-1897)"}`, Status: 403, Message: "CVE 指纹：[HW2020] ffmpeg 文件读取 (CVE-2016-1897)", SortOrder: 1055},
	{RuleID: "65562", Name: "[HW2020] ffmpeg SSRF (CVE-2016-1898)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `#EXTM3U.*(#EXT-X-TARGETDURATION|#EXT-X-MEDIA-SEQUENCE).*concat:.*#EXT-X-ENDLIST`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] ffmpeg SSRF (CVE-2016-1898)"}`, Status: 403, Message: "CVE 指纹：[HW2020] ffmpeg SSRF (CVE-2016-1898)", SortOrder: 1056},
	{RuleID: "65575", Name: "[HW2020] Kibana远程代码执行(CVE-2019-7609)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(\.es\s*\(.*\bprops\(\s*label\.__proto__\.env\.AAAA\s*=\s*.*\brequire\b.*\bchild_process\b.*\bexec)|(\.es\(\*\)\.props\(.+\.__proto__\..+)`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] Kibana远程代码执行(CVE-2019-7609)"}`, Status: 403, Message: "CVE 指纹：[HW2020] Kibana远程代码执行(CVE-2019-7609)", SortOrder: 1057},
	{RuleID: "65615", Name: "[HW2021] WebSphere 权限提升漏洞(CVE-2020-4276)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `<\?xml.+<LoginMethod>TokenBased</LoginMethod>.+<token>`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2021] WebSphere 权限提升漏洞(CVE-2020-4276)"}`, Status: 403, Message: "CVE 指纹：[HW2021] WebSphere 权限提升漏洞(CVE-2020-4276)", SortOrder: 1058},
	{RuleID: "65888", Name: ".Net 反序列化 - XML", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)type\s*=\s*"[^"]*(System\.Windows\.Data\.ObjectDataProvider|System\.Web\.Security\.RolePrincipal|System\.IdentityModel\.Tokens\.SessionSecurityToken|System\.Web\.UI\.MobileControls\.SessionViewState\+SessionViewStateHistoryItem|Microsoft\.IdentityModel\.Claims\.WindowsClaimsIdentity|System\.Security\.Principal\.WindowsIdentity|System\.Security\.Principal\.WindowsPrincipal)[^"]*"`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：.Net 反序列化 - XML"}`, Status: 403, Message: "CVE 指纹：.Net 反序列化 - XML", SortOrder: 1059},
	{RuleID: "65763", Name: "异常的文件上传", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)Content-Disposition:(([^\r\n\t\f\v:]| )+(\r\n?|\r?\n)){2,}[^\r\n:]+:`,
		Transforms: `[]`, Vars: `[{"type":"BODY"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：异常的文件上传"}`, Status: 403, Message: "CVE 指纹：异常的文件上传", SortOrder: 1060},
	{RuleID: "65576", Name: "[HW2020] HFS RCE", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `^\x00\{.+\}`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","specific":"search"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] HFS RCE"}`, Status: 403, Message: "CVE 指纹：[HW2020] HFS RCE", SortOrder: 1061},
	{RuleID: "65776", Name: "[HW2023] pbootcms CNVD-2021-32163 SQL 注入", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\{pboot:sql`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","specific":"keyword"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2023] pbootcms CNVD-2021-32163 SQL 注入"}`, Status: 403, Message: "CVE 指纹：[HW2023] pbootcms CNVD-2021-32163 SQL 注入", SortOrder: 1062},
	{RuleID: "65746", Name: "OpenTSDB 2.4.0 远程代码执行(CVE-2020-35476)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\[33:(system|exec|passthru|shell_exec|popen)\w*\(.*\)\w*\]`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：OpenTSDB 2.4.0 远程代码执行(CVE-2020-35476)"}`, Status: 403, Message: "CVE 指纹：OpenTSDB 2.4.0 远程代码执行(CVE-2020-35476)", SortOrder: 1063},
	{RuleID: "65875", Name: "mongodb nosql 注入-query", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\[\$(ne|eq|lt|lte|gt|gte|ni|nin|mod|all|size|exists|type|slice|or|xor|nor|div|between|and|not|regex|text|where|jsonSchema|elemMatch)\]`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","parse":["keys"]}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：mongodb nosql 注入-query"}`, Status: 403, Message: "CVE 指纹：mongodb nosql 注入-query", SortOrder: 1064},
	{RuleID: "65589", Name: "DEDECMS SQL 注入漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `arrs\d\[`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","parse":["keys"]}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：DEDECMS SQL 注入漏洞"}`, Status: 403, Message: "CVE 指纹：DEDECMS SQL 注入漏洞", SortOrder: 1065},
	{RuleID: "65706", Name: "Drupal 内核远程代码执行漏洞 (CVE-2018-7602)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(q\s*\[[\s\S]*(?i)(post_render|lazy_builder|pre_render|access_callback|submit|validate)\][\s\S]*=\s*((assert|shell_exec|exec|passthru|system|popen|proc_open|pcntl_exec)|(var_dump|var_export|print_r)))`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","specific":"destination"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Drupal 内核远程代码执行漏洞 (CVE-2018-7602)"}`, Status: 403, Message: "CVE 指纹：Drupal 内核远程代码执行漏洞 (CVE-2018-7602)", SortOrder: 1066},
	{RuleID: "65753", Name: "Dedecms 远程代码注入 (CVE-2018-7700)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\{\s*dede\s*:\s*field\s+name\s*=\s*'source'\s*runphp\s*=\s*'yes'\}`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","specific":"partcode"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Dedecms 远程代码注入 (CVE-2018-7700)"}`, Status: 403, Message: "CVE 指纹：Dedecms 远程代码注入 (CVE-2018-7700)", SortOrder: 1067},
	{RuleID: "65569", Name: "[HW2020] MetInfo 前台 SQL 注入 (CNVD-2018-20024)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `^dosafety_emailadd$`,
		Transforms: `[]`, Vars: `[{"type":"URI_ARGS","specific":"a"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] MetInfo 前台 SQL 注入 (CNVD-2018-20024)"}`, Status: 403, Message: "CVE 指纹：[HW2020] MetInfo 前台 SQL 注入 (CNVD-2018-20024)", SortOrder: 1068},
	{RuleID: "65699", Name: "Apache Solr 远程代码执行漏洞 (CVE-2019-0193)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^(\s*<dataConfig>[\s\S]*<script>[\s\S]*function[\s\S]*\{[\s\S]*([\d\w_]+)\([\s\S]*\)[\s\S]*\}[\s\S]*<\/script>[\s\S]*<\/dataConfig>)`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"dataConfig"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Apache Solr 远程代码执行漏洞 (CVE-2019-0193)"}`, Status: 403, Message: "CVE 指纹：Apache Solr 远程代码执行漏洞 (CVE-2019-0193)", SortOrder: 1069},
	{RuleID: "65631", Name: "科蓝反序列化漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `_savedMap|_dataMap`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","parse":["keys"]}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：科蓝反序列化漏洞"}`, Status: 403, Message: "CVE 指纹：科蓝反序列化漏洞", SortOrder: 1070},
	{RuleID: "65651", Name: "Java 代码注入漏洞 (针对 Struts 2 漏洞的通用防御)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((getClass[\s\S]*forName[\s\S]*java(\s*\.\s*)lang(\s*\.\s*)Runtime([\s\S]*)getMethod([\s\S]*)exec)|(com(\s*\.\s*)sun(\s*\.\s*)org(\s*\.\s*)apache(\s*\.\s*)bcel(\s*\.\s*)internal(\s*\.\s*)util(\s*\.\s*)ClassLoader))`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Java 代码注入漏洞 (针对 Struts 2 漏洞的通用防御)"}`, Status: 403, Message: "CVE 指纹：Java 代码注入漏洞 (针对 Struts 2 漏洞的通用防御)", SortOrder: 1071},
	{RuleID: "65716", Name: "PHPCMS v9.6.0 任意文件上传", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\.php#`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"info[content]"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：PHPCMS v9.6.0 任意文件上传"}`, Status: 403, Message: "CVE 指纹：PHPCMS v9.6.0 任意文件上传", SortOrder: 1072},
	{RuleID: "65665", Name: "Spring 框架漏洞", Group: "cve", Phase: "access", Severity: 1, Enabled: true,
		Operator: `REGEX`, Pattern: `T\(`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","parse":["keys"]}]`,
		Actions: `{"disrupt":"SCORE","value":2,"msg":"CVE 指纹：Spring 框架漏洞（累积计分，需多特征叠加）"}`, Status: 200, Message: "CVE 指纹：Spring 框架漏洞", SortOrder: 1073},
	{RuleID: "65594", Name: "ThinkPHP 5.0.x _method 代码注入", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `^__construct$`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"_method"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：ThinkPHP 5.0.x _method 代码注入"}`, Status: 403, Message: "CVE 指纹：ThinkPHP 5.0.x _method 代码注入", SortOrder: 1074},
	{RuleID: "65708", Name: "Drupalgeddon2 - Drupal核心远程代码执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `#(post_render|lazy_builder|pre_render|access_callback|submit|validate)`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","parse":["keys"]}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Drupalgeddon2 - Drupal核心远程代码执行"}`, Status: 403, Message: "CVE 指纹：Drupalgeddon2 - Drupal核心远程代码执行", SortOrder: 1075},
	{RuleID: "65710", Name: "Drupalgeddon2 - Drupal核心远程代码执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((#(post_render|lazy_builder|pre_render|access_callback|submit|validate))[\s\S]*[^_\d\w]((assert|shell_exec|exec|passthru|system|popen|proc_open|pcntl_exec)|(var_dump|var_export|print_r)))`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"ids[]"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Drupalgeddon2 - Drupal核心远程代码执行"}`, Status: 403, Message: "CVE 指纹：Drupalgeddon2 - Drupal核心远程代码执行", SortOrder: 1076},
	{RuleID: "65794", Name: "服务端包含注入", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i).*<!--#.+-->`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：服务端包含注入"}`, Status: 403, Message: "CVE 指纹：服务端包含注入", SortOrder: 1077},
	{RuleID: "65840", Name: "Maccms 8.x 远程代码执行 (CVE-2017-17733)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\{\s*if-.*\{\s*endif\-`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"wd"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Maccms 8.x 远程代码执行 (CVE-2017-17733)"}`, Status: 403, Message: "CVE 指纹：Maccms 8.x 远程代码执行 (CVE-2017-17733)", SortOrder: 1078},
	{RuleID: "65876", Name: "mongodb nosql 注入-form", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\[\$(ne|eq|lt|lte|gt|gte|ni|nin|mod|all|size|exists|type|slice|or|xor|nor|div|between|and|not|regex|text|where|jsonSchema|elemMatch)\]`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","parse":["keys"]}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：mongodb nosql 注入-form"}`, Status: 403, Message: "CVE 指纹：mongodb nosql 注入-form", SortOrder: 1079},
	{RuleID: "65707", Name: "Drupal Mail 命令注入", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `^\s*-`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"site_mail"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Drupal Mail 命令注入"}`, Status: 403, Message: "CVE 指纹：Drupal Mail 命令注入", SortOrder: 1080},
	{RuleID: "65621", Name: "[HW2021] GoAhead Server 环境变量注入漏洞(CVE-2021-42342)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `/proc/self/fd/0`,
		Transforms: `[]`, Vars: `[{"type":"POST_ARGS","specific":"LD_PRELOAD"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2021] GoAhead Server 环境变量注入漏洞(CVE-2021-42342)"}`, Status: 403, Message: "CVE 指纹：[HW2021] GoAhead Server 环境变量注入漏洞(CVE-2021-42342)", SortOrder: 1081},
	{RuleID: "65666", Name: "Spring 框架漏洞", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((.*T\(.*\)\s*\..*\(.*\))|(.*(java|spring|sun|exec|Runtime|forName).*\..*\(.*\))|(.*new\s+(\w){3,}\s*\..+\(.*\)))`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"spring.cloud.function.routing-expression"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Spring 框架漏洞"}`, Status: 403, Message: "CVE 指纹：Spring 框架漏洞", SortOrder: 1082},
	{RuleID: "65585", Name: "[HW2020] Nginx range filter overflow (CVE-2017-7529)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `bytes\s*=\s*-\d+\s*,\s*-\d{19,}`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"range"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] Nginx range filter overflow (CVE-2017-7529)"}`, Status: 403, Message: "CVE 指纹：[HW2020] Nginx range filter overflow (CVE-2017-7529)", SortOrder: 1083},
	{RuleID: "65568", Name: "[HW2020] PHPStudy 命令执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `[a-zA-Z+/]{20,}`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"accept-charset"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] PHPStudy 命令执行"}`, Status: 403, Message: "CVE 指纹：[HW2020] PHPStudy 命令执行", SortOrder: 1084},
	{RuleID: "65599", Name: "Gogs、Gitea 远程代码执行漏洞 (CVE-2018-18925)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\/`,
		Transforms: `[]`, Vars: `[{"type":"COOKIE","specific":"i_like_gogits"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：Gogs、Gitea 远程代码执行漏洞 (CVE-2018-18925)"}`, Status: 403, Message: "CVE 指纹：Gogs、Gitea 远程代码执行漏洞 (CVE-2018-18925)", SortOrder: 1085},
	{RuleID: "65596", Name: "PHPSpy 后门", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)phpspypass`,
		Transforms: `[]`, Vars: `[{"type":"COOKIE"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：PHPSpy 后门"}`, Status: 403, Message: "CVE 指纹：PHPSpy 后门", SortOrder: 1086},
	{RuleID: "65567", Name: "[HW2020] Apache Shiro 反序列化攻击 (CVE-2016-4437)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `[a-zA-Z+/0-9]{500,}`,
		Transforms: `[]`, Vars: `[{"type":"COOKIE","specific":"rememberMe"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：[HW2020] Apache Shiro 反序列化攻击 (CVE-2016-4437)"}`, Status: 403, Message: "CVE 指纹：[HW2020] Apache Shiro 反序列化攻击 (CVE-2016-4437)", SortOrder: 1087},
	{RuleID: "65597", Name: "后门", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)zerodium`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"user-agent"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：后门"}`, Status: 403, Message: "CVE 指纹：后门", SortOrder: 1088},
	{RuleID: "65695", Name: "joomla 远程代码执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\|\s*(O|a)\s*:\d+:`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"user-agent"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：joomla 远程代码执行"}`, Status: 403, Message: "CVE 指纹：joomla 远程代码执行", SortOrder: 1089},
	{RuleID: "65696", Name: "joomla 远程代码执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\|\s*(O|a)\s*:\d+:`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"x-forwarded-for"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：joomla 远程代码执行"}`, Status: 403, Message: "CVE 指纹：joomla 远程代码执行", SortOrder: 1090},
	{RuleID: "65743", Name: "ECShop 2.x/3.x SQL注入/远程代码执行", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(.)*[a-zA-Z0-9]{32}(.)*(ads)(\s)*(|)(.)*((s:3:"num";)|(s:2:"id"))(s:)[0-9]+(:")[^"]*[^0-9]*`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"referer"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：ECShop 2.x/3.x SQL注入/远程代码执行"}`, Status: 403, Message: "CVE 指纹：ECShop 2.x/3.x SQL注入/远程代码执行", SortOrder: 1091},
	{RuleID: "65720", Name: "代码注入漏洞 (针对 WordPress)", Group: "cve", Phase: "access", Severity: 2, Enabled: true,
		Operator: `REGEX`, Pattern: `\$\{`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"host"}]`,
		Actions: `{"disrupt":"LOG_ONLY","status":200,"msg":"CVE 指纹：代码注入漏洞 (针对 WordPress)"}`, Status: 200, Message: "CVE 指纹：代码注入漏洞 (针对 WordPress)", SortOrder: 1092},
	{RuleID: "65789", Name: "异常的文件上传 (Content-Type)", Group: "cve", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)boundary.*=.*=\?[a-zA-Z0-9-_]+\?(b|q).*\?=`,
		Transforms: `[]`, Vars: `[{"type":"HEADERS","specific":"content-type"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"CVE 指纹：异常的文件上传 (Content-Type)"}`, Status: 403, Message: "CVE 指纹：异常的文件上传 (Content-Type)", SortOrder: 1093},
}
