// Code generated from chaitin/safeline libfusion2.so deserialization rules (逆向提取). DO NOT EDIT BY HAND.
package model

// SeedRulesDeser 反序列化攻击检测规则（逆向 libfusion2.so rskynet 反序列化模块提取）
// 覆盖：Java 原生序列化/class 字节码/BCEL/反射链/OGNL/SpEL/freemarker/XStream/Jackson/JNDI/
//       Commons-Collections gadget/.NET BinaryFormatter/fastjson @type 等已知反序列化攻击特征
// 默认 BLOCK 403，可在后台改为 LOG_ONLY
var SeedRulesDeser = []Rule{
	{RuleID: "65900", Name: "Java 反序列化 gadget 链特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(java\.beans\.EventHandler|java\.lang\.ProcessBuilder|javax\.imageio\.ImageIO\$ContainsFilter|jdk\.nashorn\.internal\.objects\.NativeString|com\.sun\.corba\.se\.impl\.activation\.ServerTableEntry|com\.sun\.tools\.javac\.processing\.JavacProcessingEnvironment\$NameProcessIterator|sun\.awt\.datatransfer\.DataTransferer\$IndexOrderComparator|sun\.swing\.SwingLazyValue|org\.springframework\.cglib\.core\.ReflectUtils|org\.springframework\.util\.Base64Utils|java\.net\.URL\b|(\(['"])?java\.lang\.Runtime(['"]\))?.getRuntime\(+\)+\.|javax\.naming\.ldap|T\(java\.lang\.Runtime\)\.getRuntime\(\)\.exec|\.getClass\(\s*\)\.forName|\.getEngineByName|(\\*["']\s*\.\s*execute\(\s*\))|java\.lang\.System\.setProperty|java\.util\.Scanner|Runtime\.getRuntime\(\)\.exec|On\s*Error\s*Resume\s*Next|(freemarker\.template\.utility\.)|(["']@type["']\s*:\s*[^"]([a-zA-Z_][\w]{0,30}(\.[a-zA-Z_][\w]{0,30})+["]))|require\s*\(\s*'child_process'\s*\)|java\s*\.\s*lang\s*\.\s*System["') ]|getClass\s*\(\s*\)\s*\.\s*getMethod\s*\(\s*|class\s*\.\s*forName|org\s*\.\s*springframework\s*\.\s*expression\s*\.\s*spel|nc\s*\.\s*itf\s*\.\s*hr\s*\.\s*tools\s*\.\s*IFileTrans|WScript\s*\.\s*CreateObject|java\s*\.\s*lang\s*\.\s*Runtime"\?new\(\)\s*\.\s*getRuntime|getClass\(\)\s*\.\s*getProtectionDomain\(\)\s*\.\s*getCodeSource\(\))`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：Java 反序列化 gadget 链特征（YsoSerial/内存马/命令执行）"}`, Status: 403, Message: "反序列化：Java 反序列化 gadget 链特征（YsoSerial/内存马/命令执行）", SortOrder: 2000},
	{RuleID: "65901", Name: "Java 序列化数据包头特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^rO0AB[a-zA-Z0-9\/+ ]{30,}`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"COOKIE"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：Java 原生序列化数据（rO0AB 头）疑似反序列化攻击"}`, Status: 403, Message: "反序列化：Java 原生序列化数据（rO0AB 头）疑似反序列化攻击", SortOrder: 2001},
	{RuleID: "65902", Name: "Java Class 字节码特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^yv66vgAAAD[a-zA-Z0-9\/+ ]{40,}`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：内嵌 Java Class 字节码（yv66vg 魔数）疑似恶意类加载"}`, Status: 403, Message: "反序列化：内嵌 Java Class 字节码（yv66vg 魔数）疑似恶意类加载", SortOrder: 2002},
	{RuleID: "65903", Name: "BCEL Class 字节码特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)^\$\$BCEL\$\$(\$[a-z0-9A-Z_]*){20,}`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：BCEL ClassLoader 字节码攻击载荷"}`, Status: 403, Message: "反序列化：BCEL ClassLoader 字节码攻击载荷", SortOrder: 2003},
	{RuleID: "65904", Name: "反射链 Class.forName+Runtime+exec", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)((getClass[\s\S]*forName[\s\S]*java(\s*\.\s*)lang(\s*\.\s*)Runtime([\s\S]*)getMethod([\s\S]*)exec)|(com(\s*\.\s*)sun(\s*\.\s*)org(\s*\.\s*)apache(\s*\.\s*)bcel(\s*\.\s*)internal(\s*\.\s*)util(\s*\.\s*)ClassLoader))`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：反射链调用（forName+getMethod+exec）反序列化 RCE"}`, Status: 403, Message: "反序列化：反射链调用（forName+getMethod+exec）反序列化 RCE", SortOrder: 2004},
	{RuleID: "65905", Name: "XStream 反序列化 RCE (CVE-2021-29505)", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\<java\.rmi\.server\.RemoteObject\>`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：XStream 反序列化 RCE（RemoteObject 特征）"}`, Status: 403, Message: "反序列化：XStream 反序列化 RCE（RemoteObject 特征）", SortOrder: 2005},
	{RuleID: "65906", Name: "Jackson 反序列化 JNDI (CVE-2020-36188)", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(com\.newrelic\.agent\.deps\.ch\.qos\.logback\.core\.db\.JNDIConnectionSource|com\.sun\.rowset\.JdbcRowSetImpl)`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：Jackson/JNDI 注入 gadget 类加载特征"}`, Status: 403, Message: "反序列化：Jackson/JNDI 注入 gadget 类加载特征", SortOrder: 2006},
	{RuleID: "65907", Name: "JNDI LDAP/RMI 注入特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(\bldap\s*://[\w|\.|\/|\-]*|rmi\s*://[\w|\.|\/|\-]*|^(\x24\x7b.*(jndi|ldap|rmi)))`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"},{"type":"HEADERS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：JNDI 注入（LDAP/RMI 协议外连）Log4j/反序列化"}`, Status: 403, Message: "反序列化：JNDI 注入（LDAP/RMI 协议外连）Log4j/反序列化", SortOrder: 2007},
	{RuleID: "65908", Name: "Freemarker 模板注入 RCE", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `\$\{.*"freemarker\.template\.utility\.Execute"\s*\?new|freemarker\.template\.utility\.Execute`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：Freemarker 模板注入（Execute 内置对象）RCE"}`, Status: 403, Message: "反序列化：Freemarker 模板注入（Execute 内置对象）RCE", SortOrder: 2008},
	{RuleID: "65909", Name: "Struts2 OGNL 注入特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `.*(\(|\{).*(java\.io\.File|java\.lang\.ProcessBuilder|java\.lang\.Runtime|java\.lang\.System|java\.lang\.Class|java\.lang\.ClassLoader|java\.lang\.Shutdown|javax\.script\.ScriptEngineManager|ognl\.OgnlContext|ognl\.MemberAccess|ognl\.ClassResolver|ognl\.TypeConverter|com\.opensymphony\.xwork2\.ActionContext|_memberAccess)`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：Struts2 OGNL 表达式注入 RCE"}`, Status: 403, Message: "反序列化：Struts2 OGNL 表达式注入 RCE", SortOrder: 2009},
	{RuleID: "65910", Name: "OGNL _memberAccess 绕过链", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `^(\(\s*["']|[^']*'\s[\+;]\s*\()?\s*((#|\\43)_memberAccess)(\.{1,}|\s*[\[=])`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：OGNL _memberAccess 权限绕过链（Struts2 系列漏洞）"}`, Status: 403, Message: "反序列化：OGNL _memberAccess 权限绕过链（Struts2 系列漏洞）", SortOrder: 2010},
	{RuleID: "65911", Name: "Commons-Collections 经典 gadget 链", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)java\.util\.\.*(Comparator|comparator)|com\.sun\.org\.apache\.xalan\.internal\.xsltc\.trax\.TemplatesImpl|org\.apache\.commons\.collections\.functors\.InvokerTransformer|org\.springframework\.aop\.framework\.JdkDynamicAopProxy|java\.lang\.Comparable|jdk\.nashorn\.internal\.runtime\.Source|org\.apache\.commons\.beanutils\.BeanComparator|sun\.reflect\.annotation\.AnnotationInvocationHandler|javax\.management\.BadAttributeValueExpException|org\.codehaus\.groovy\.runtime|sun\.tracing\.`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：Commons-Collections/Beanutils 经典反序列化 gadget 链"}`, Status: 403, Message: "反序列化：Commons-Collections/Beanutils 经典反序列化 gadget 链", SortOrder: 2011},
	{RuleID: "65912", Name: "反序列化 RMI 服务对象引用", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)\<java\.rmi\.server\.RemoteObject\>|java\.rmi\.server\.UnicastRef|java\.rmi\.dgc\.Lease`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：反序列化 RMI 远程对象引用（JRMP 攻击）"}`, Status: 403, Message: "反序列化：反序列化 RMI 远程对象引用（JRMP 攻击）", SortOrder: 2012},
	{RuleID: "65913", Name: ".NET BinaryFormatter 反序列化", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `(?i)(System\.Management\.Automation\.PSObject|System\.Collections\.Generic\.SortedSet|System\.DelegateSerializationHolder\+DelegateEntry|System\.IdentityModel\.Tokens\.SessionSecurityToken)`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：.NET BinaryFormatter 反序列化攻击（PSObject/进程启动）"}`, Status: 403, Message: "反序列化：.NET BinaryFormatter 反序列化攻击（PSObject/进程启动）", SortOrder: 2013},
	{RuleID: "65914", Name: "fastjson 反序列化 @type 特征", Group: "deser", Phase: "access", Severity: 3, Enabled: true,
		Operator: `REGEX`, Pattern: `["']@type["']\s*:\s*[^"]([a-zA-Z_][\w]{0,30}(\.[a-zA-Z_][\w]{0,30})+["])`,
		Transforms: `[]`, Vars: `[{"type":"BODY"},{"type":"POST_ARGS"},{"type":"URI_ARGS"}]`,
		Actions: `{"disrupt":"BLOCK","status":403,"msg":"反序列化：fastjson @type 自动类型反序列化攻击特征"}`, Status: 403, Message: "反序列化：fastjson @type 自动类型反序列化攻击特征", SortOrder: 2014},
}
